spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/opt/workspaces/np-microservices-sample-01/np-ms-sample-01-config
  security:
    user:
      password: topsecret
         